// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package output

//go:nosplit
//go:noescape
//goland:noinspection ALL
func __native_entry__() uintptr

var (
    _subr__sum = __native_entry__() + 13
)

const (
    _stack__sum = 0
)

var (
    _ = _subr__sum
)

const (
    _ = _stack__sum
)
